2022-07-30 17:37:49,428 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.106:5000 (Press CTRL+C to quit)
2022-07-30 17:39:42,969 INFO werkzeug Thread-1 : 127.0.0.1 - - [30/Jul/2022 17:39:42] "[33mGET / HTTP/1.1[0m" 404 -
2022-07-30 17:40:01,254 INFO rest_server_app Thread-2 : application pinged...
2022-07-30 17:40:01,255 INFO werkzeug Thread-2 : 127.0.0.1 - - [30/Jul/2022 17:40:01] "GET /ping HTTP/1.1" 200 -
2022-08-31 17:06:15,319 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-08-31 17:57:54,646 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-08-31 18:10:09,751 INFO werkzeug Thread-1 : 127.0.0.1 - - [31/Aug/2022 18:10:09] "[33mGET /users/api/v1 HTTP/1.1[0m" 404 -
2022-08-31 18:10:18,723 INFO werkzeug Thread-2 : 127.0.0.1 - - [31/Aug/2022 18:10:18] "GET /users/api/v1/ping HTTP/1.1" 200 -
2022-08-31 21:41:04,916 ERROR rest_server_app Thread-3 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 21, in login
    return jsonify(user)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:41:12,090 INFO werkzeug Thread-3 : 127.0.0.1 - - [31/Aug/2022 21:41:12] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:49:11,023 ERROR rest_server_app Thread-4 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 21, in login
    return jsonify(user)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:49:11,067 INFO werkzeug Thread-4 : 127.0.0.1 - - [31/Aug/2022 21:49:11] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:49:19,388 ERROR rest_server_app Thread-5 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 21, in login
    return jsonify(user)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:49:19,389 INFO werkzeug Thread-5 : 127.0.0.1 - - [31/Aug/2022 21:49:19] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:49:47,681 ERROR rest_server_app Thread-6 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 21, in login
    return jsonify(user)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:49:47,682 INFO werkzeug Thread-6 : 127.0.0.1 - - [31/Aug/2022 21:49:47] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:49:58,849 INFO werkzeug Thread-7 : 127.0.0.1 - - [31/Aug/2022 21:49:58] "GET /users/api/v1/ping HTTP/1.1" 200 -
2022-08-31 21:50:16,372 ERROR rest_server_app Thread-8 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 21, in login
    return jsonify(user)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:50:16,373 INFO werkzeug Thread-8 : 127.0.0.1 - - [31/Aug/2022 21:50:16] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:50:25,526 ERROR rest_server_app Thread-9 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 21, in login
    return jsonify(user)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:50:25,527 INFO werkzeug Thread-9 : 127.0.0.1 - - [31/Aug/2022 21:50:25] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:51:33,913 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-08-31 21:51:38,688 INFO werkzeug Thread-1 : 127.0.0.1 - - [31/Aug/2022 21:51:38] "POST /users/api/v1/login HTTP/1.1" 200 -
2022-08-31 21:52:19,321 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-08-31 21:52:25,084 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 21, in login
    return jsonify(user)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:52:25,121 INFO werkzeug Thread-1 : 127.0.0.1 - - [31/Aug/2022 21:52:25] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:54:27,470 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-08-31 21:54:31,737 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 21, in login
    return json.dumps(user)
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:54:31,739 INFO werkzeug Thread-1 : 127.0.0.1 - - [31/Aug/2022 21:54:31] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:54:48,754 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-08-31 21:54:51,106 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 21, in login
    print(json.dumps(user))
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:54:51,111 INFO werkzeug Thread-1 : 127.0.0.1 - - [31/Aug/2022 21:54:51] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:55:16,416 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-08-31 21:55:18,620 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 22, in login
    print(json.dumps(user))
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:55:18,625 INFO werkzeug Thread-1 : 127.0.0.1 - - [31/Aug/2022 21:55:18] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:56:43,544 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-08-31 21:56:49,262 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 22, in login
    print(json.loads(user))
  File "/usr/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
2022-08-31 21:56:49,264 INFO werkzeug Thread-1 : 127.0.0.1 - - [31/Aug/2022 21:56:49] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:57:17,012 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-08-31 21:57:20,538 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 25, in login
    return json.dumps(user)
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:57:20,540 INFO werkzeug Thread-1 : 127.0.0.1 - - [31/Aug/2022 21:57:20] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:57:29,023 ERROR rest_server_app Thread-2 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 25, in login
    return json.dumps(user)
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:57:29,024 INFO werkzeug Thread-2 : 127.0.0.1 - - [31/Aug/2022 21:57:29] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:59:53,625 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-08-31 21:59:57,891 INFO werkzeug Thread-1 : 127.0.0.1 - - [31/Aug/2022 21:59:57] "POST /users/api/v1/login HTTP/1.1" 200 -
2022-08-31 22:00:08,353 INFO werkzeug Thread-2 : 127.0.0.1 - - [31/Aug/2022 22:00:08] "POST /users/api/v1/login HTTP/1.1" 200 -
